#!/usr/bin/env python

import chess
import chess.pgn
from StringIO import StringIO

# parse data from text file by using
# python-chess

with open('eco.txt') as f:
    lines = f.readlines()

out = []
for line  in lines:
    if not line.strip() == '':
        eco = line[0:3]
        split = line[3:].split('"')
        game = split[0]
        text = ""
        if len(split) > 1: 
            text = split[1]
        pgn = StringIO(game)
        pychess_game = chess.pgn.read_game(pgn)
        zobrist = pychess_game.end().board().zobrist_hash()
        zob_hex = hex(zobrist)
        zobrist_cpp = zob_hex[:len(zob_hex)-1] + "ULL"
        out.append((eco, zobrist_cpp, text))

# write down the parsed data into static const QMap
# to include in Jerry

print("static const QMap<unsigned long, EcoInfo> ECOINFOS { ")
l = len(out)
for i, (eco,zobrist,text) in enumerate(out):
    # add comma only if not last line
    if i < l-1:
        print('    {"' + zobrist + '", {' + eco + ', "' + text + '"}},')
    else:
        print('    {"' + zobrist + '", {' + eco + ', "' + text + '"}}')
print("};")
        

